# Generated by Django 4.2.16 on 2024-10-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopName', models.CharField(max_length=255)),
                ('Address', models.TextField()),
                ('Phone', models.CharField(max_length=15)),
            ],
        ),
    ]
